In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [3]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
arr_3d= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [5]:
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
arr_3d.ndim

3

In [8]:
arr = np.ones((3,3))

In [9]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr.ndim

2

In [11]:
arr = np.zeros((3,3))

In [12]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr = np.arange(2,10,2)

In [18]:
arr

array([2, 4, 6, 8])

In [21]:
import numpy as np
arr = np.linspace(1,10,4)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr.strides)
print(arr.flags)

[ 1.  4.  7. 10.]
(4,)
1
4
float64
8
32
(8,)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [24]:
arr = np.linspace(0,2,4)

In [25]:
arr

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [28]:
import numpy as np
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d.shape)

(2, 2, 3)


In [30]:
arr_3d.reshape((15))

ValueError: cannot reshape array of size 12 into shape (15,)

In [34]:
arr = np.array([1,'str',3,4])

In [36]:
print(arr)

['1' 'str' '3' '4']


In [38]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print('The mean of the array is:',arr.mean())
print('The standard deviation of the array is:',arr.std())
print('The variance of the array is:',arr.var())
print('The minimum value of the array is:',arr.min())
print('The maximum value of the array is:',arr.max())
print('The sum of the array is:',arr.sum())

The mean of the array is: 5.5
The standard deviation of the array is: 2.8722813232690143
The variance of the array is: 8.25
The minimum value of the array is: 1
The maximum value of the array is: 10
The sum of the array is: 55


In [39]:
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
print(arr_2d[2][2])

9


In [49]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
arr_1d[1:3]

array([2, 3])

In [51]:
arr = np.array([2,4,5,8])

np.where(arr>4, 1, 0)

array([0, 0, 1, 1])

In [52]:
import time  

# Define two Python lists 
py_list1 = list(range(1000000)) 
py_list2 = list(range(1000000, 2000000))  

# Define two Numpy arrays 
np_array1 = np.arange(1000000) 
np_array2 = np.arange(1000000, 2000000)  

# Adding Python lists 
start_time = time.time() 
result_list = [a + b for a, b in zip(py_list1, py_list2)] 
print("Time taken to add Python lists: ", time.time() - start_time)  

# Adding Numpy arrays 
start_time = time.time() 
result_array = np_array1 + np_array2 
print("Time taken to add Numpy arrays: ", time.time() - start_time)

Time taken to add Python lists:  0.0741419792175293
Time taken to add Numpy arrays:  0.001994609832763672
